replicaCount: 2

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""  # Sera surchargé dynamiquement via --set image.tag=...

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts: []
  tls: []

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "default"  # Surchargé dynamiquement via values-<env>.yaml

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
