env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

replicaCount: 3

resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

ingress:
  enabled: true
  hosts:
    - host: mon-app.prod.mondomaine.com
      paths:
        - path: /
          pathType: Prefix
