#replicaCount: 4
namespace: staging

env:
  API_HOST: "adbbafe0aa8bc44eca9cd4bd0d8d9779-2044885311.ca-central-1.elb.amazonaws.com"
  API_PORT: "80"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#service:
#  type: Loadbalancer
