apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.MYSQL_ROOT_PASSWORD | quote }}
  MYSQL_ROOT_USER: {{ .Values.secrets.MYSQL_ROOT_USER | default | quote }}

