apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.MARIADB_ROOT_PASSWORD | quote }}
  MARIADB_DATABASE: {{ .Values.secrets.MARIADB_DATABASE | quote }}
  MARIADB_ROOT_USER: {{ .Values.secrets.MARIADB_ROOT_USER | quote }}
