apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80        # Exposé à l’extérieur (LoadBalancer)
      targetPort: 8080 # Port réel dans ton container
#    - name: https
#      protocol: TCP
#      port: 443       # Exposé à l’extérieur (LoadBalancer)
#      targetPort: 8443 # Port réel dans ton container

