apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST:  {{ .Values.env.DB_HOST | quote }}
  DB_PORT:  {{ .Values.env.DB_PORT | quote }}
  DB_NAME:  {{ .Values.env.DB_NAME | quote }}

